# Dependencies
gems:
  - jekyll-paginate

# Permalinks
permalink:         pretty

# Setup
url:               "https://patuellimalagola.github.io"

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl:           ''

title:             Azienda Agricola Patuelli-Malagola

# Pagination
paginate:          5
paginate_path:     '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:       >
  Pagina in costruzione.

# The tags listed as entries in the sidebar
sidebar_tags:      []

# Fallback image and color if not overwritten for tag or post
image:             /patuellimalagola.github.io/public/img/uva.jpg
color:             '#A85641'

# Fonts
font:              '"PT Serif", Georgia, serif'
font_accent:       '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts: 'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name:            'Sandra Giuliani'

  # This photo will be used in the about section, add url here
  #photo:           

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:           |
    Hi there.

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    #facebook:      <username>
    #twitter:       <username>
    #google:        <number>
   # vk:            <username>
    #youtube:       <string>_<string>_<string>
    # vimeo:         <username>
    # lastfm:        <username>
    # instagram:     <username>
    # flickr:        <string>@<string>
    # ello:          <username>
    # twitch:        <username>
    # steam:         <number>
    # reddit:        <username>
    # tumblr:        <username>
    #linkedin:        https://www.linkedin.com/company/azienda-agricola-patuelli-malagola-di-giuliani-anna-e-sandra
    # paypal:        <username>

# Setting a disqus subdomain will enable the comment section
#disqus:            <username>

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
